version: "3.8"

services:
    postgres:
        image: postgres
        restart: always
        container_name: postgres_pi
        ports:
            - "5432:5432"
        env_file:
            - .env
        volumes:
            - ./postgres-data:/var/lib/postgresql
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin_pi
        restart: always
        user: '$UID:$GID'
        env_file:
            - .env
        ports:
            - 5050:80
        depends_on:
            - postgres
        volumes:
            - ./pgadmin:/var/lib/pgadmin

volumes:
    pgadmin:
    postgres-data: